version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      #- ./nginx/nginx-custom.conf:/etc/nginx/conf.d/nginx_custom.conf:ro
      #- ./nginx/self-signed-certificate:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: dapp_nginx
  app:
    build: docker/app/
    volumes:
      - ./:/var/www/html:rw
    environment:
      - VIRTUAL_HOST=dapp.TCM.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    container_name: TCM_dapp
  
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  
  browser-solidity:
    build: browser-solidity
    ports:
      - "8080:8080"
    container_name: Solidity_browser

  go-ethereum:
    image: ethereum/client-go
    container_name: 'eth'
    volumes:
    - "./chaindata:/root/.ethereum" #  remplacer /srv/eth/datadir par le chemin ou vous voulez stocker la blockchain
    ports:
    - 30303:30303
    - 8545:8545 # Port JSON RPC, optionnel
    command: geth -datadir=chaindata init /etherum-genesis/genesis.json --rpc --rpccorsdomain "*" --rpcaddr "0.0.0.0" --rpcport "8545" --rpcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3"  --networkid 1  --nat "any" --syncmode=light console
